version: "3.8"
services:

  vite:
    container_name: vite
    build:
      context: ./vite
    restart: on-failure
    volumes:
      - ./vite:/usr/src/app
    networks:
      - backend

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    restart: always
    volumes:
      - ./vite/dist:/var/www/dist
    ports:
      - 80:80
    networks:
      - backend

networks:
  backend:
