version: "3.8"
services:

  vite:
    container_name: vite
    build:
      context: ./vite
    env_file: .env
    restart: on-failure
    volumes:
      - ./vite:/usr/src/app
    networks:
      - transcendence

  postgres:
    container_name: postgres
    image: postgres:alpine
    env_file: .env
    restart: unless-stopped
    volumes:
      - postgres-dat:/var/lib/postgresql/data
    networks:
      - transcendence
    ports:
      - 5432:5432

  nest:
    container_name: nest
    build:
      context: ./nest
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./nest:/usr/src/app
    networks:
      - transcendence

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./vite/dist:/var/www/dist
    ports:
      - 8080:8080
    networks:
      - transcendence

volumes:
  postgres-dat:

networks:
  transcendence:
