version: "3"

services:
  db:
    container_name: db
    image: postgres
    # restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    # ports a retirer plus tard
    ports:
      - 5432:5432

  adminer:
    container_name: adminer
    image: adminer
    # restart: always
    ports:
      - 8080:8080

  nestjs:
    container_name: nestjs
    build:
      context: .
      dockerfile_inline: |
        FROM node
        RUN mkdir -p /app && chown node:node /app
        WORKDIR /app
        COPY --chown=node:node package*.json ./
        USER node
        RUN npm install
        COPY --chown=node:node . .
        RUN npm run build
        CMD ["npm", "run", "start"]
    # bind-mount volumes (ne pas utiliser a 42)
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    ports:
      - 3000:3000

volumes:
  postgres_data:
