version: "3.8"
services:

  vite:
    container_name: vite
    build:
      context: ./vite
    env_file: .env
    restart: on-failure
    volumes:
      - ./vite:/usr/src/app
    networks:
      - backend

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    env_file: .env
    restart: always
    volumes:
      - ./vite/dist:/var/www/dist
    ports:
      - 8080:8080
    networks:
      - backend

networks:
  backend:
