version: "3"

services:
  db:
    image: postgres
    # restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

  adminer:
    image: adminer
    # restart: always
    ports:
      - 8080:8080

  nestjs:
    build:
      context: .
      dockerfile_inline: |
        FROM node
        RUN mkdir /app && chown node:node /app
        WORKDIR /app
        COPY --chown=node:node package*.json ./
        USER node
        RUN npm install
        COPY --chown=node:node . .
        RUN npm run build
        CMD ["npm", "run", "start"]
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000

volumes:
  postgres_data:
