FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --omit=dev

# Move node modules to parent directory so it isn't overwritten when volume is mounted
RUN mv node_modules ../

CMD [ "./launch.sh" ]
